//checking if user is logged in
###
GET https://localhost:3000/api/users/logged HTTP/1.1
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InN0MTAxMjEwNjUiLCJ1c2VyaWQiOiI2MzQ0MTFjMzM3Mzk4MmJiNzFmYzcyMTAiLCJpYXQiOjE2NjU0MDY0OTcsImV4cCI6MTY2NTQxMDA5N30.csN7Towah2owE6wPPGD8BEU3bc2gwyi9t-DiPJ4pyh4
//Registering new user 
###
POST https://localhost:3000/api/users/register HTTP/1.1
content-Type: application/json

{
    "id" : "st10121065@gmail.com",
    "password" : "mypassword1"
}
//loggin in  users
###
POST https://localhost:3000/api/users/login HTTP/1.1 
content-type: application/json

 {
     "id": "michael@gmail.com", 
     "password": "password" 
 }

###
DELETE https://localhost:3000/api/users/63369c7eb6223747cb867ca1 HTTP/1.1
 
 //Checks Authoirzation
###
GET https://localhost:3000/api/dash HTTP/1.1
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzZXIyIiwidXNlcmlkIjoiNjM0MDBiN2NlZmEyYTg2Y2M1NjYxMDNiIiwiaWF0IjoxNjY1MTQxODY1LCJleHAiOjE2NjUxNDU0NjV9.cAlYxy3LOewWKjqIBg3-l2Yo2wIkXJFFOypJ2k-NfeQ
//Displays posts 
###
GET https://localhost:3000/api/dash/displayPosts HTTP/1.1
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY2hhZWxAZ21haWwuY29tIiwidXNlcmlkIjoiNjM2MjZjMzU1MGM0NTM5MjE3ZTQyMWE5IiwiaWF0IjoxNjY3Mzk1NDMwLCJleHAiOjE2NjczOTkwMzB9.kuGjRwE-10lo8NYWQRmKWA0zDx9HuI5efFm4euH890k
###
POST https://localhost:3000/api/dash/addPost HTTP/1.1
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InN0MTAxMjEwNjUiLCJ1c2VyaWQiOiI2MzQ0MTFjMzM3Mzk4MmJiNzFmYzcyMTAiLCJpYXQiOjE2NjU0MDY0OTcsImV4cCI6MTY2NTQxMDA5N30.csN7Towah2owE6wPPGD8BEU3bc2gwyi9t-DiPJ4pyh4
//Registering new user 

{
    "title":"Post number 2",
    "description": "This is the second post to say the work has started for the new area!"
}
//Deletes Posts
###
DELETE  https://localhost:3000/api/dash/deletePost/634418ff14167f0497da3c1f HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InN0MTAxMjEwNjUiLCJ1c2VyaWQiOiI2MzQ0MTFjMzM3Mzk4MmJiNzFmYzcyMTAiLCJpYXQiOjE2NjU0MDY0OTcsImV4cCI6MTY2NTQxMDA5N30.csN7Towah2owE6wPPGD8BEU3bc2gwyi9t-DiPJ4pyh4

